filter:
    excluded_paths: [vendor/*, test/*]

before_commands:
    - "composer install --dev --prefer-source"

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_analyzer: true
    php_code_coverage: true